# Singular Value Decomposition (SVD)

## Python Implementation

Topics Covered

1. Creating Matrices
2. Computing SVD
3. Understanding U Matrix
4. Understanding Singular Values
5. Understanding Vᵀ Matrix
6. Matrix Reconstruction
7. Rank using SVD
8. Low Rank Approximation
9. Compression using SVD
10. PCA Connection
11. Noise Reduction
12. AI Applications

In [2]:
import numpy as np

np.set_printoptions(
    precision=4,
    suppress=True
)

print("NumPy Version:", np.__version__)

NumPy Version: 2.4.6


# Creating a Matrix

We start with a simple matrix:

$$
A=
\begin{bmatrix}
1 & 2 \\
3 & 4 \\
5 & 6
\end{bmatrix}
$$

In [3]:
A = np.array([
    [1,2],
    [3,4],
    [5,6]
])

print(A)

[[1 2]
 [3 4]
 [5 6]]


# Computing SVD

SVD factorizes a matrix as:

$$
A = U \Sigma V^T
$$

In [4]:
U, S, VT = np.linalg.svd(A)

print("U Matrix:\n")
print(U)

print("\nSingular Values:\n")
print(S)

print("\nV^T Matrix:\n")
print(VT)

U Matrix:

[[-0.2298  0.8835  0.4082]
 [-0.5247  0.2408 -0.8165]
 [-0.8196 -0.4019  0.4082]]

Singular Values:

[9.5255 0.5143]

V^T Matrix:

[[-0.6196 -0.7849]
 [-0.7849  0.6196]]


# Understanding U Matrix

U contains Left Singular Vectors.

Properties:

$$
U^TU = I
$$

In [5]:
print(
    np.round(
        U.T @ U,
        4
    )
)

[[ 1.  0.  0.]
 [ 0.  1. -0.]
 [ 0. -0.  1.]]


# Understanding Singular Values

Singular values indicate how important each direction is.

Larger values contain more information.

In [6]:
for i, value in enumerate(S):

    print(
        f"σ{i+1} = {value:.4f}"
    )

σ1 = 9.5255
σ2 = 0.5143


# Understanding Vᵀ

Rows of Vᵀ are Right Singular Vectors.

Properties:

$$
V^TV = I
$$

In [7]:
print(
    np.round(
        VT @ VT.T,
        4
    )
)

[[1. 0.]
 [0. 1.]]


# Building Sigma Matrix

NumPy returns singular values separately.

We convert them into a diagonal matrix.

In [8]:
Sigma = np.zeros(
    (A.shape[0], A.shape[1])
)

np.fill_diagonal(
    Sigma,
    S
)

print(Sigma)

[[9.5255 0.    ]
 [0.     0.5143]
 [0.     0.    ]]


# Matrix Reconstruction

Using:

$$
A = U\Sigma V^T
$$

we should recover the original matrix.

In [9]:
A_reconstructed = (
    U @ Sigma @ VT
)

print(
    np.round(
        A_reconstructed,
        4
    )
)

[[1. 2.]
 [3. 4.]
 [5. 6.]]


# Reconstruction Error

Difference between original and reconstructed matrix.

In [10]:
error = np.linalg.norm(
    A - A_reconstructed
)

print(
    "Error:",
    error
)

Error: 1.3911054626160788e-15


# Rank from SVD

Rank equals the number of non-zero singular values.

In [11]:
rank = np.sum(
    S > 1e-10
)

print(
    "Rank:",
    rank
)

Rank: 2


# Low Rank Approximation

Keep only the largest singular value.

In [12]:
k = 1

U_k = U[:, :k]

S_k = np.diag(
    S[:k]
)

VT_k = VT[:k, :]

A_k = (
    U_k
    @
    S_k
    @
    VT_k
)

print(
    np.round(
        A_k,
        4
    )
)

[[1.3566 1.7185]
 [3.0972 3.9233]
 [4.8378 6.1281]]


# Information Retained

Measure how much information remains.

In [13]:
retained = (
    np.sum(S[:1])
    /
    np.sum(S)
)

print(
    f"{retained*100:.2f}%"
)

94.88%


# Example: Larger Matrix

In [14]:
A = np.random.randint(
    1,
    10,
    (5,5)
)

print(A)

[[5 4 1 9 8]
 [1 8 2 2 4]
 [5 6 6 9 3]
 [6 4 8 6 8]
 [9 7 4 1 1]]


In [15]:
U,S,VT = np.linalg.svd(A)

print("Singular Values:\n")

print(S)

Singular Values:

[26.0486  8.6075  5.8293  4.6152  4.3703]


# Condition Number

Measures numerical stability.

$$
\kappa=
\frac{\sigma_{max}}
{\sigma_{min}}
$$

In [16]:
condition_number = (
    S.max()
    /
    S.min()
)

print(
    condition_number
)

5.960370692823416


# Noise Reduction Idea

Small singular values often correspond to noise.

In [17]:
A = np.random.rand(
    10,
    10
)

U,S,VT = np.linalg.svd(A)

S_filtered = S.copy()

S_filtered[5:] = 0

Sigma_filtered = np.zeros(
    (10,10)
)

np.fill_diagonal(
    Sigma_filtered,
    S_filtered
)

A_denoised = (
    U
    @
    Sigma_filtered
    @
    VT
)

print(
    A_denoised.shape
)

(10, 10)


# Connection with Eigenvalues

For:

$$
A^TA
$$

Singular values are:

$$
\sigma_i=\sqrt{\lambda_i}
$$

In [18]:
A = np.array([
    [1,2],
    [3,4]
])

ATA = A.T @ A

eigenvalues, _ = np.linalg.eig(
    ATA
)

print(
    "Eigenvalues:\n",
    eigenvalues
)

print(
    "\nSquare Root:\n",
    np.sqrt(eigenvalues)
)

Eigenvalues:
 [ 0.1339 29.8661]

Square Root:
 [0.366 5.465]


# PCA using SVD

In [19]:
from sklearn.decomposition import PCA

data = np.random.randn(
    100,
    5
)

pca = PCA()

pca.fit(data)

print(
    pca.explained_variance_
)

[1.4619 1.2309 1.1835 0.8225 0.6489]


# Recommendation System Concept

User-Item Matrix

In [20]:
ratings = np.array([
    [5,4,0,1],
    [4,0,0,1],
    [1,1,0,5],
    [1,0,0,4],
    [0,1,5,4]
])

U,S,VT = np.linalg.svd(
    ratings
)

print(
    "Latent Factors:"
)

print(S)

Latent Factors:
[9.1687 6.4046 3.8625 2.2354]


# Embedding Compression

Large embedding matrices can be compressed using SVD.

This is widely used in modern AI systems.

# Key Takeaways

✅ Every matrix can be decomposed:

$$
A = U\Sigma V^T
$$

✅ Singular values measure importance.

✅ Rank equals number of non-zero singular values.

✅ SVD provides optimal low-rank approximations.

✅ PCA is built on SVD.

✅ SVD is one of the most important mathematical tools in AI and Machine Learning.