# Systems of Linear Equations

## Python Implementation

In this notebook we will learn:

1. Solving Systems using NumPy
2. Matrix Inverse Method
3. Gaussian Elimination from Scratch
4. Cramer's Rule
5. Interactive System Solver
6. AI Applications

---

In [1]:
import numpy as np

print("NumPy Version:", np.__version__)

NumPy Version: 2.4.6


# Example System

$$
\begin{cases}
2x+y=5 \\
x-y=1
\end{cases}
$$

Matrix Form:

$$
AX=B
$$

$$
A=
\begin{bmatrix}
2 & 1 \\
1 & -1
\end{bmatrix}
$$

$$
B=
\begin{bmatrix}
5 \\
1
\end{bmatrix}
$$

In [2]:
A = np.array([
    [2, 1],
    [1, -1]
])

B = np.array([
    5,
    1
])

print("A =\n", A)
print("\nB =\n", B)

A =
 [[ 2  1]
 [ 1 -1]]

B =
 [5 1]


# Solving Using NumPy

NumPy provides the `linalg.solve()` function.

In [3]:
solution = np.linalg.solve(A, B)

print("Solution:")
print("x =", solution[0])
print("y =", solution[1])

Solution:
x = 2.0
y = 1.0


# Matrix Inverse Method

The solution is:

$$
X=A^{-1}B
$$

In [4]:
A_inv = np.linalg.inv(A)

solution = A_inv @ B

print("Inverse Matrix:\n")
print(A_inv)

print("\nSolution:")
print(solution)

Inverse Matrix:

[[ 0.33333333  0.33333333]
 [ 0.33333333 -0.66666667]]

Solution:
[2. 1.]


# Determinant

A matrix is invertible only if:

$$
det(A)\neq0
$$

In [5]:
determinant = np.linalg.det(A)

print("Determinant =", determinant)

Determinant = -2.9999999999999996


# Gaussian Elimination From Scratch

We solve the system using row operations.

In [6]:
def gaussian_elimination(A, B):

    A = A.astype(float)
    B = B.astype(float)

    n = len(B)

    for i in range(n):

        pivot = A[i][i]

        A[i] = A[i] / pivot
        B[i] = B[i] / pivot

        for j in range(i + 1, n):

            factor = A[j][i]

            A[j] -= factor * A[i]
            B[j] -= factor * B[i]

    x = np.zeros(n)

    for i in range(n - 1, -1, -1):

        x[i] = B[i]

        for j in range(i + 1, n):
            x[i] -= A[i][j] * x[j]

    return x

In [7]:
A = np.array([
    [2,1],
    [1,-1]
])

B = np.array([
    5,
    1
])

solution = gaussian_elimination(A, B)

print("Solution:")
print(solution)

Solution:
[2. 1.]


# Cramer's Rule

For:

$$
AX=B
$$

$$
x=\frac{D_x}{D}
$$

$$
y=\frac{D_y}{D}
$$

In [8]:
A = np.array([
    [2,1],
    [1,-1]
])

B = np.array([
    5,
    1
])

D = np.linalg.det(A)

Dx = np.linalg.det(np.array([
    [5,1],
    [1,-1]
]))

Dy = np.linalg.det(np.array([
    [2,5],
    [1,1]
]))

x = Dx / D
y = Dy / D

print("x =", x)
print("y =", y)

x = 2.0000000000000004
y = 1.0


# Solving a 3×3 System

Real-world AI systems often involve thousands or millions of equations.

In [9]:
A = np.array([
    [1,1,1],
    [2,-1,1],
    [1,2,-1]
])

B = np.array([
    6,
    3,
    3
])

solution = np.linalg.solve(A, B)

print(solution)

[1.28571429 2.14285714 2.57142857]


# Interactive System Solver

Adjust coefficients and instantly solve the system.

In [10]:
from ipywidgets import interact
from ipywidgets import FloatSlider

In [11]:
def solve_system(a,b,c,d,e,f):

    A = np.array([
        [a,b],
        [d,e]
    ])

    B = np.array([
        c,
        f
    ])

    try:

        solution = np.linalg.solve(A,B)

        print("x =", round(solution[0],4))
        print("y =", round(solution[1],4))

    except:

        print("No unique solution")

In [12]:
interact(
    solve_system,

    a=FloatSlider(min=-10,max=10,value=2),
    b=FloatSlider(min=-10,max=10,value=1),
    c=FloatSlider(min=-20,max=20,value=5),

    d=FloatSlider(min=-10,max=10,value=1),
    e=FloatSlider(min=-10,max=10,value=-1),
    f=FloatSlider(min=-20,max=20,value=1)
);

interactive(children=(FloatSlider(value=2.0, description='a', max=10.0, min=-10.0), FloatSlider(value=1.0, des…

# AI Application

## Linear Regression Normal Equation

One of the most famous systems of equations in Machine Learning:

$$
(X^TX)\theta = X^Ty
$$

Solving this equation gives the optimal parameters for linear regression.

In [13]:
X = np.array([
    [1,1],
    [1,2],
    [1,3],
    [1,4]
])

y = np.array([
    2,
    3,
    4,
    5
])

theta = np.linalg.inv(
    X.T @ X
) @ (X.T @ y)

print("Parameters:")
print(theta)

Parameters:
[1. 1.]


# Key Takeaways

✅ Matrix Representation

✅ NumPy Solver

✅ Matrix Inverse Method

✅ Gaussian Elimination

✅ Cramer's Rule

✅ Interactive Solver

✅ AI Applications

Systems of Linear Equations are one of the most important foundations of Machine Learning, Deep Learning, Robotics, Optimization, and Scientific Computing.