# Systems of Linear Equations Visualization

## Interactive Learning Lab

In this notebook you will explore:

- Line Intersections
- Unique Solutions
- No Solutions
- Infinite Solutions
- Matrix Transformations
- Determinants
- Geometric Interpretation

Use the sliders to modify equations and instantly visualize the results.

In [1]:
import numpy as np
import matplotlib.pyplot as plt

from ipywidgets import interact
from ipywidgets import FloatSlider

plt.rcParams["figure.figsize"] = (8, 6)

# Visualizing Two Linear Equations

Equation 1:

$$
a_1x+b_1y=c_1
$$

Equation 2:

$$
a_2x+b_2y=c_2
$$

Move the sliders and observe how the solution changes.

In [2]:
def plot_system(a1,b1,c1,a2,b2,c2):

    x = np.linspace(-10,10,400)

    plt.figure(figsize=(8,6))

    if b1 != 0:
        y1 = (c1 - a1*x)/b1
        plt.plot(x,y1,label='Equation 1')

    if b2 != 0:
        y2 = (c2 - a2*x)/b2
        plt.plot(x,y2,label='Equation 2')

    A = np.array([
        [a1,b1],
        [a2,b2]
    ])

    B = np.array([c1,c2])

    try:
        solution = np.linalg.solve(A,B)

        plt.scatter(
            solution[0],
            solution[1],
            s=150
        )

        plt.annotate(
            f"({solution[0]:.2f},{solution[1]:.2f})",
            (solution[0],solution[1])
        )

        title = "Unique Solution"

    except:
        title = "No Unique Solution"

    plt.grid(True)
    plt.legend()
    plt.title(title)

    plt.xlim(-10,10)
    plt.ylim(-10,10)

    plt.show()

In [3]:
interact(
    plot_system,

    a1=FloatSlider(min=-10,max=10,value=2),
    b1=FloatSlider(min=-10,max=10,value=1),
    c1=FloatSlider(min=-20,max=20,value=5),

    a2=FloatSlider(min=-10,max=10,value=1),
    b2=FloatSlider(min=-10,max=10,value=-1),
    c2=FloatSlider(min=-20,max=20,value=1)
);

interactive(children=(FloatSlider(value=2.0, description='a1', max=10.0, min=-10.0), FloatSlider(value=1.0, de…

# Determinant Explorer

The determinant tells us whether a unique solution exists.

$$
det(A)
$$

- det(A) ≠ 0 → Unique Solution
- det(A) = 0 → No Unique Solution

In [4]:
def determinant_explorer(a,b,c,d):

    A = np.array([
        [a,b],
        [c,d]
    ])

    det = np.linalg.det(A)

    plt.figure(figsize=(6,6))

    origin = np.array([[0,0],[a,c],[a+b,c+d],[b,d]])

    x = origin[:,0]
    y = origin[:,1]

    plt.fill(x,y,alpha=0.3)

    plt.plot(
        [0,a],[0,c],
        linewidth=3
    )

    plt.plot(
        [0,b],[0,d],
        linewidth=3
    )

    plt.title(
        f"Determinant = {det:.2f}"
    )

    plt.grid(True)
    plt.axis('equal')

    plt.show()

In [5]:
interact(
    determinant_explorer,

    a=FloatSlider(min=-5,max=5,value=2),
    b=FloatSlider(min=-5,max=5,value=1),
    c=FloatSlider(min=-5,max=5,value=1),
    d=FloatSlider(min=-5,max=5,value=-1)
);

interactive(children=(FloatSlider(value=2.0, description='a', max=5.0, min=-5.0), FloatSlider(value=1.0, descr…

# Unique vs Infinite vs No Solution

Observe how changing coefficients changes the geometry.

In [6]:
def solution_type(k):

    x = np.linspace(-10,10,300)

    plt.figure(figsize=(8,6))

    y1 = x + 2

    y2 = k*x + 2

    plt.plot(x,y1,label="Line 1")
    plt.plot(x,y2,label="Line 2")

    if abs(k-1) < 0.001:
        title = "Infinite Solutions"
    else:
        title = "Unique Solution"

    plt.title(title)

    plt.grid(True)
    plt.legend()

    plt.show()

In [ ]:
interact(
    solution_type,

    k=FloatSlider(
        min=-3,
        max=3,
        step=0.05,
        value=1
    )
);

interactive(children=(FloatSlider(value=1.0, description='k', max=3.0, min=-3.0, step=0.05), Output()), _dom_c…

# Matrix Transformation View

A system of equations can also be interpreted as a matrix transformation.

The columns of a matrix transform the coordinate system.

In [8]:
def matrix_transform(a,b,c,d):

    A = np.array([
        [a,b],
        [c,d]
    ])

    vectors = np.array([
        [1,0],
        [0,1]
    ])

    transformed = A @ vectors

    plt.figure(figsize=(7,7))

    plt.quiver(
        [0,0],
        [0,0],
        vectors[:,0],
        vectors[:,1],
        angles='xy',
        scale_units='xy',
        scale=1
    )

    plt.quiver(
        [0,0],
        [0,0],
        transformed[0],
        transformed[1],
        angles='xy',
        scale_units='xy',
        scale=1
    )

    plt.xlim(-10,10)
    plt.ylim(-10,10)

    plt.grid(True)

    plt.title("Matrix Transformation")

    plt.show()

In [ ]:
interact(
    matrix_transform,

    a=FloatSlider(min=-5,max=5,value=2),
    b=FloatSlider(min=-5,max=5,value=1),
    c=FloatSlider(min=-5,max=5,value=1),
    d=FloatSlider(min=-5,max=5,value=-1)
);

interactive(children=(FloatSlider(value=2.0, description='a', max=5.0, min=-5.0), FloatSlider(value=1.0, descr…

# Gaussian Elimination Animation

Watch row operations transform the augmented matrix into Row Echelon Form.

In [10]:
from IPython.display import clear_output
import time

A = np.array([
    [2,1,5],
    [1,-1,1]
],dtype=float)

for step in range(2):

    clear_output(wait=True)

    print(f"Step {step+1}")
    print(A)

    time.sleep(1)

    pivot = A[step][step]

    A[step] = A[step]/pivot

    if step == 0:
        factor = A[1][0]
        A[1] -= factor*A[0]

print("\nFinal Row Echelon Form")
print(A)

Step 2
[[ 1.   0.5  2.5]
 [ 0.  -1.5 -1.5]]

Final Row Echelon Form
[[ 1.   0.5  2.5]
 [-0.   1.   1. ]]


# AI Application

Linear Regression solves a system of equations:

$$
(X^TX)\theta = X^Ty
$$

This is why Systems of Linear Equations are fundamental to Machine Learning, Deep Learning, Robotics, Control Systems, and Scientific Computing.