# Rank

## Python Implementation

In this notebook, you will learn:

1. Matrix Rank using NumPy
2. Full Rank Matrices
3. Rank Deficient Matrices
4. Row and Column Dependencies
5. Rank and Determinants
6. Rank and Linear Systems
7. Rank-Nullity Theorem
8. Rank using SVD
9. Low-Rank Approximation
10. Rank in Machine Learning

In [1]:
import numpy as np

print("NumPy Version:", np.__version__)

NumPy Version: 2.4.6


# What is Rank?

Rank is the number of linearly independent rows or columns in a matrix.

$$
Rank(A)
$$

It measures the amount of independent information contained in a matrix.

In [2]:
A = np.array([
    [1, 2],
    [3, 4]
])

print(A)

[[1 2]
 [3 4]]


In [3]:
rank = np.linalg.matrix_rank(A)

print("Rank =", rank)

Rank = 2


# Full Rank Matrix

A matrix is full rank when:

$$
Rank(A)=\min(m,n)
$$

In [4]:
A = np.array([
    [1, 2],
    [3, 4]
])

print(A)

print(
    "\nRank:",
    np.linalg.matrix_rank(A)
)

[[1 2]
 [3 4]]

Rank: 2


# Rank Deficient Matrix

Rows or columns contain redundant information.

In [5]:
A = np.array([
    [1,2],
    [2,4]
])

print(A)

print(
    "\nRank:",
    np.linalg.matrix_rank(A)
)

[[1 2]
 [2 4]]

Rank: 1


# Row Dependency

The second row is a multiple of the first row.
$$
R_2 = 2R_1
$$

Therefore rank decreases.

In [6]:
A = np.array([
    [1,2,3],
    [2,4,6],
    [3,6,9]
])

print(A)

print(
    "\nRank:",
    np.linalg.matrix_rank(A)
)

[[1 2 3]
 [2 4 6]
 [3 6 9]]

Rank: 1


# Column Dependency

Columns can also be linearly dependent.

In [7]:
A = np.array([
    [1,2],
    [2,4],
    [3,6]
])

print(A)

print(
    "\nRank:",
    np.linalg.matrix_rank(A)
)

[[1 2]
 [2 4]
 [3 6]]

Rank: 1


# Rank and Determinants

If:

$$
det(A)\neq0
$$

then:

$$
Rank(A)=n
$$

In [8]:
A = np.array([
    [2,3],
    [1,4]
])

det = np.linalg.det(A)

rank = np.linalg.matrix_rank(A)

print("Determinant =", det)

print("Rank =", rank)

Determinant = 5.000000000000001
Rank = 2


# Singular Matrix

A singular matrix has:

$$
det(A)=0
$$

and reduced rank.

In [9]:
A = np.array([
    [1,2],
    [2,4]
])

print(
    "Determinant:",
    np.linalg.det(A)
)

print(
    "Rank:",
    np.linalg.matrix_rank(A)
)

Determinant: 0.0
Rank: 1


# Rank and Linear Systems

Consider:

$$
AX=B
$$

The rank determines whether a solution exists.

In [10]:
A = np.array([
    [2,1],
    [1,-1]
])

B = np.array([
    5,
    1
])

solution = np.linalg.solve(A,B)

print(solution)

[2. 1.]


# Rank-Nullity Theorem

$$
Rank(A)+Nullity(A)=n
$$

where:

n = number of columns.

In [11]:
A = np.array([
    [1,2,3],
    [2,4,6]
])

rank = np.linalg.matrix_rank(A)

n = A.shape[1]

nullity = n - rank

print("Rank =", rank)

print("Nullity =", nullity)

Rank = 1
Nullity = 2


# Rank using Singular Value Decomposition (SVD)

SVD is one of the most powerful tools in AI and Machine Learning.

In [12]:
A = np.array([
    [1,2],
    [3,4]
])

U,S,Vt = np.linalg.svd(A)

print("Singular Values:")

print(S)

Singular Values:
[5.4649857  0.36596619]


In [13]:
rank = np.sum(S > 1e-10)

print("Rank =", rank)

Rank = 2


# Low Rank Approximation

Many AI systems compress information using low-rank approximations.

In [14]:
A = np.random.rand(5,5)

U,S,Vt = np.linalg.svd(A)

k = 2

A_low_rank = (
    U[:,:k]
    @ np.diag(S[:k])
    @ Vt[:k,:]
)

print("Original Shape:", A.shape)

print(
    "Approximation Shape:",
    A_low_rank.shape
)

Original Shape: (5, 5)
Approximation Shape: (5, 5)


# Rank in Machine Learning Datasets

Rank tells us how many independent features exist.

In [15]:
dataset = np.array([
    [1,2,3],
    [2,4,6],
    [3,6,9],
    [4,8,12]
])

print(dataset)

print(
    "\nFeature Rank:",
    np.linalg.matrix_rank(dataset)
)

[[ 1  2  3]
 [ 2  4  6]
 [ 3  6  9]
 [ 4  8 12]]

Feature Rank: 1


# Rank in PCA

Principal Component Analysis identifies directions that preserve the maximum rank-related information.

PCA reduces dimensionality while retaining important structure.

In [16]:
covariance_matrix = np.array([
    [4,2],
    [2,3]
])

eigenvalues, eigenvectors = np.linalg.eig(
    covariance_matrix
)

print("Eigenvalues:")

print(eigenvalues)

Eigenvalues:
[5.56155281 1.43844719]


# Random Matrix Rank Analysis

In [17]:
for size in [2,3,4,5]:

    A = np.random.randint(
        1,
        10,
        (size,size)
    )

    rank = np.linalg.matrix_rank(A)

    print("\nMatrix Size:", size)

    print(A)

    print("Rank =", rank)


Matrix Size: 2
[[3 8]
 [6 1]]
Rank = 2

Matrix Size: 3
[[6 4 9]
 [3 9 2]
 [5 7 1]]
Rank = 3

Matrix Size: 4
[[2 6 7 5]
 [3 2 1 7]
 [9 7 5 7]
 [5 5 5 9]]
Rank = 4

Matrix Size: 5
[[4 5 3 1 1]
 [1 9 3 2 4]
 [5 4 4 1 2]
 [4 5 1 9 5]
 [5 3 7 2 7]]
Rank = 5


# Rank and Data Compression

Modern AI systems often compress information using low-rank structures.

Examples:

- PCA
- Recommender Systems
- Image Compression
- Language Models
- Embedding Models