# 🧮 Matrix Operations in Python

In this notebook, we will implement:

1. Creating Matrices
2. Matrix Addition
3. Matrix Subtraction
4. Scalar Multiplication
5. Matrix Multiplication
6. Element-wise Multiplication
7. Matrix Transpose
8. Identity Matrix
9. Matrix Determinant
10. Matrix Inverse
11. Matrix Rank
12. Matrix Trace
13. Matrix Operations using NumPy
14. Matrix Operations in Artificial Intelligence

Matrix operations form the computational foundation of Machine Learning and Deep Learning.

In [1]:
import numpy as np

np.set_printoptions(
    precision=3,
    suppress=True
)

print("NumPy Successfully Imported")

NumPy Successfully Imported


# 1️⃣ Creating Matrices

A matrix is a rectangular arrangement of numbers.

Example:

$$
A=
\begin{bmatrix}
1 & 2\\
3 & 4
\end{bmatrix}
$$

In [2]:
A = np.array([
    [1,2],
    [3,4]
])

B = np.array([
    [5,6],
    [7,8]
])

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]


# 2️⃣ Matrix Addition

Matrices with the same dimensions can be added element-wise.

In [3]:
result = A + B

print("A + B =")
print(result)

A + B =
[[ 6  8]
 [10 12]]


# 3️⃣ Matrix Subtraction

Subtract corresponding elements from two matrices.

In [4]:
result = B - A

print("B - A =")
print(result)

B - A =
[[4 4]
 [4 4]]


# 4️⃣ Scalar Multiplication

Multiply every element of a matrix by a scalar value.

In [5]:
scalar = 3

result = scalar * A

print(result)

[[ 3  6]
 [ 9 12]]


# 5️⃣ Matrix Multiplication

Matrix multiplication combines rows of one matrix with columns of another matrix.

This is one of the most important operations in AI.

In [6]:
result = A @ B

print("A × B =")
print(result)

A × B =
[[19 22]
 [43 50]]


# Understanding Dimensions

If:

$$
A_{m \times n}
$$

and

$$
B_{n \times p}
$$

Then:
$$
AB_{m \times p}
$$

In [7]:
print("Shape of A:", A.shape)
print("Shape of B:", B.shape)

print("\nResult Shape:")
print((A @ B).shape)

Shape of A: (2, 2)
Shape of B: (2, 2)

Result Shape:
(2, 2)


# 6️⃣ Element-wise Multiplication

Also called the Hadamard Product.

Every element is multiplied by its corresponding element.

In [8]:
result = A * B

print(result)

[[ 5 12]
 [21 32]]


# 7️⃣ Matrix Transpose

Transpose converts rows into columns.

In [9]:
A_transpose = A.T

print("A:")
print(A)

print("\nAᵀ:")
print(A_transpose)

A:
[[1 2]
 [3 4]]

Aᵀ:
[[1 3]
 [2 4]]


# 8️⃣ Identity Matrix

The identity matrix is the matrix equivalent of the number 1.

$$
AI=A
$$

In [10]:
I = np.eye(3)

print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
A = np.array([
    [2,3],
    [1,4]
])

I = np.eye(2)

print(A @ I)

[[2. 3.]
 [1. 4.]]


# 9️⃣ Matrix Determinant

The determinant measures how much a matrix scales space.

For a 2×2 matrix:

$$
det(A)=ad-bc
$$

In [12]:
A = np.array([
    [2,3],
    [1,4]
])

determinant = np.linalg.det(A)

print("Determinant:")
print(determinant)

Determinant:
5.000000000000001


# 🔟 Matrix Inverse

The inverse reverses a matrix transformation.

$$
AA^{-1}=I
$$

In [13]:
A = np.array([
    [2,3],
    [1,4]
])

inverse = np.linalg.inv(A)

print("Inverse Matrix:")
print(inverse)

Inverse Matrix:
[[ 0.8 -0.6]
 [-0.2  0.4]]


In [14]:
print("Verification:")

print(
    np.round(
        A @ inverse,
        decimals=5
    )
)

Verification:
[[ 1. -0.]
 [ 0.  1.]]


# 1️⃣1️⃣ Matrix Rank

Rank represents the number of independent rows or columns.

In [15]:
A = np.array([
    [1,2],
    [2,4]
])

rank = np.linalg.matrix_rank(A)

print("Rank:", rank)

Rank: 1


In [16]:
A = np.array([
    [1,2],
    [3,4]
])

print(
    np.linalg.matrix_rank(A)
)

2


# 1️⃣2️⃣ Matrix Trace

The trace is the sum of diagonal elements.

$$
tr(A)
=
a_{11}+a_{22}+...
$$

In [17]:
A = np.array([
    [1,2],
    [3,4]
])

trace = np.trace(A)

print(trace)

5


# 1️⃣3️⃣ Useful NumPy Matrix Functions

NumPy provides many optimized matrix operations.

In [18]:
A = np.array([
    [1,2],
    [3,4]
])

print("Transpose:")
print(A.T)

print("\nDeterminant:")
print(np.linalg.det(A))

print("\nInverse:")
print(np.linalg.inv(A))

print("\nRank:")
print(np.linalg.matrix_rank(A))

print("\nTrace:")
print(np.trace(A))

Transpose:
[[1 3]
 [2 4]]

Determinant:
-2.0000000000000004

Inverse:
[[-2.   1. ]
 [ 1.5 -0.5]]

Rank:
2

Trace:
5


# 1️⃣4️⃣ Matrix Operations in Neural Networks

A neural network layer computes:

$$
y = Wx+b
$$

where:

- W = Weight Matrix
- x = Input Vector
- b = Bias Vector

This operation is essentially matrix multiplication.

In [19]:
input_vector = np.array([
    1.0,
    2.0,
    3.0
])

weights = np.array([
    [0.5,0.2,0.1],
    [0.4,0.8,0.3]
])

bias = np.array([
    0.1,
    0.2
])

output = weights @ input_vector + bias

print("Input:")
print(input_vector)

print("\nOutput:")
print(output)

Input:
[1. 2. 3.]

Output:
[1.3 3.1]


# Mini Neural Network Example

Input → Matrix Multiplication → Output

In [20]:
X = np.array([
    [1,2],
    [3,4],
    [5,6]
])

W = np.array([
    [0.5,0.2],
    [0.8,0.4]
])

Y = X @ W

print(Y)

[[2.1 1. ]
 [4.7 2.2]
 [7.3 3.4]]


# Matrix Operations Behind Transformers

Transformers use matrix multiplication extensively.

Examples:

$$
QK^T
$$

$$
Attention = Softmax(QK^T)V
$$

Every token is represented as a vector and transformed through matrices.

In [21]:
Q = np.random.rand(4,3)
K = np.random.rand(4,3)

attention_scores = Q @ K.T

print(attention_scores)

[[0.922 0.894 0.442 0.183]
 [0.248 0.376 0.226 0.213]
 [0.896 1.188 0.694 0.573]
 [0.373 0.655 0.426 0.444]]


# 📊 Summary

In this notebook, you learned:

✅ Matrix Creation

✅ Matrix Addition

✅ Matrix Subtraction

✅ Scalar Multiplication

✅ Matrix Multiplication

✅ Element-wise Multiplication

✅ Transpose

✅ Identity Matrix

✅ Determinant

✅ Inverse

✅ Rank

✅ Trace

✅ NumPy Matrix Operations

✅ Neural Network Computation

These operations are the foundation of:

- Machine Learning
- Deep Learning
- Computer Vision
- Reinforcement Learning
- Transformers
- Large Language Models