# 🎨 Matrix Operations Visualization

## Objectives

This notebook visualizes:

1. Matrix Addition
2. Matrix Subtraction
3. Scalar Multiplication
4. Matrix Multiplication
5. Matrix Transformations
6. Matrix Determinant
7. Matrix Inverse
8. Matrix Rank
9. Neural Network Matrix Flow

---

Visualization helps build intuition about how matrices transform vectors, shapes, and data.

These same operations power:

- Neural Networks
- Transformers
- Computer Vision
- Robotics
- Reinforcement Learning

In [1]:
import numpy as np
import matplotlib.pyplot as plt

from ipywidgets import interact
from ipywidgets import FloatSlider

plt.rcParams["figure.figsize"] = (8,8)

# 1️⃣ Matrix Addition Visualization

Observe how two vectors combine through addition.

Matrix addition can be understood as combining transformations.

In [2]:
def vector_addition(x1,y1,x2,y2):

    plt.figure(figsize=(8,8))

    plt.quiver(
        0,0,x1,y1,
        angles='xy',
        scale_units='xy',
        scale=1
    )

    plt.quiver(
        0,0,x2,y2,
        angles='xy',
        scale_units='xy',
        scale=1
    )

    plt.quiver(
        0,0,
        x1+x2,
        y1+y2,
        angles='xy',
        scale_units='xy',
        scale=1
    )

    plt.xlim(-10,10)
    plt.ylim(-10,10)

    plt.grid(True)

    plt.title("Vector Addition")

    plt.show()

interact(
    vector_addition,
    x1=(-5,5,0.5),
    y1=(-5,5,0.5),
    x2=(-5,5,0.5),
    y2=(-5,5,0.5)
);

interactive(children=(FloatSlider(value=0.0, description='x1', max=5.0, min=-5.0, step=0.5), FloatSlider(value…

# 2️⃣ Scalar Multiplication Explorer

A scalar scales every element of a matrix.

Move the slider to stretch or compress the shape.

In [ ]:
square = np.array([
    [0,0],
    [1,0],
    [1,1],
    [0,1],
    [0,0]
])

def scalar_scale(k):

    transformed = square * k

    plt.figure(figsize=(8,8))

    plt.plot(
        square[:,0],
        square[:,1],
        linewidth=3,
        label="Original"
    )

    plt.plot(
        transformed[:,0],
        transformed[:,1],
        linewidth=3,
        label="Scaled"
    )

    plt.grid(True)

    plt.legend()

    plt.title(
        f"Scalar = {k:.2f}"
    )

    plt.show()

interact(
    scalar_scale,
    k=(-5,5,0.1)
);

interactive(children=(FloatSlider(value=0.0, description='k', max=5.0, min=-5.0), Output()), _dom_classes=('wi…

# 3️⃣ Matrix Multiplication Transformation

Matrix multiplication creates geometric transformations.

Adjust matrix values and observe the transformation.

In [ ]:
shape = np.array([
    [0,0],
    [1,0],
    [1,1],
    [0,1],
    [0,0]
])

def matrix_transform(a,b,c,d):

    A = np.array([
        [a,b],
        [c,d]
    ])

    transformed = shape @ A.T

    plt.figure(figsize=(8,8))

    plt.plot(
        shape[:,0],
        shape[:,1],
        linewidth=3,
        label="Original"
    )

    plt.plot(
        transformed[:,0],
        transformed[:,1],
        linewidth=3,
        label="Transformed"
    )

    plt.xlim(-10,10)
    plt.ylim(-10,10)

    plt.grid(True)

    plt.legend()

    plt.title(
        f"Matrix\n{A}"
    )

    plt.show()

interact(
    matrix_transform,
    a=(-3,3,0.1),
    b=(-3,3,0.1),
    c=(-3,3,0.1),
    d=(-3,3,0.1)
);

interactive(children=(FloatSlider(value=0.0, description='a', max=3.0, min=-3.0), FloatSlider(value=0.0, descr…

# 4️⃣ Determinant Visualizer

The determinant measures area scaling.

Observe how the area changes as the determinant changes.

In [5]:
def determinant_visualizer(k):

    A = np.array([
        [k,0],
        [0,1]
    ])

    shape = np.array([
        [0,0],
        [1,0],
        [1,1],
        [0,1],
        [0,0]
    ])

    transformed = shape @ A.T

    determinant = np.linalg.det(A)

    plt.figure(figsize=(8,8))

    plt.fill(
        transformed[:,0],
        transformed[:,1],
        alpha=0.3
    )

    plt.plot(
        transformed[:,0],
        transformed[:,1]
    )

    plt.grid(True)

    plt.title(
        f"Determinant = {determinant:.2f}"
    )

    plt.xlim(-6,6)
    plt.ylim(-6,6)

    plt.show()

interact(
    determinant_visualizer,
    k=(-5,5,0.1)
);

interactive(children=(FloatSlider(value=0.0, description='k', max=5.0, min=-5.0), Output()), _dom_classes=('wi…

# 5️⃣ Matrix Inverse Explorer

A matrix inverse reverses a transformation.

Apply a transformation and then its inverse.

In [6]:
def inverse_demo(scale):

    A = np.array([
        [scale,0],
        [0,scale]
    ])

    inverse = np.linalg.inv(A)

    point = np.array([2,1])

    transformed = A @ point

    recovered = inverse @ transformed

    print("Original :", point)
    print("Transformed :", transformed)
    print("Recovered :", recovered)

interact(
    inverse_demo,
    scale=(0.5,5,0.1)
);

interactive(children=(FloatSlider(value=2.7, description='scale', max=5.0, min=0.5), Output()), _dom_classes=(…

# 6️⃣ Rank Visualization

Rank measures the number of independent directions.

If rows become dependent, rank decreases.

In [7]:
def rank_visualizer(k):

    A = np.array([
        [1,2],
        [k,2*k]
    ])

    rank = np.linalg.matrix_rank(A)

    print("Matrix:\n")
    print(A)

    print("\nRank =", rank)

interact(
    rank_visualizer,
    k=(-5,5,0.1)
);

interactive(children=(FloatSlider(value=0.0, description='k', max=5.0, min=-5.0), Output()), _dom_classes=('wi…

# 7️⃣ Interactive Matrix Playground

Experiment with any 2×2 matrix and see its effect on the coordinate grid.

This is one of the best ways to understand linear algebra visually.

In [8]:
def grid_transform(a,b,c,d):

    A = np.array([
        [a,b],
        [c,d]
    ])

    plt.figure(figsize=(9,9))

    for x in range(-5,6):

        line = np.array([
            [x,-5],
            [x,5]
        ])

        transformed = line @ A.T

        plt.plot(
            transformed[:,0],
            transformed[:,1]
        )

    for y in range(-5,6):

        line = np.array([
            [-5,y],
            [5,y]
        ])

        transformed = line @ A.T

        plt.plot(
            transformed[:,0],
            transformed[:,1]
        )

    plt.xlim(-15,15)
    plt.ylim(-15,15)

    plt.grid(True)

    plt.title(
        f"Transformation Matrix\n{A}"
    )

    plt.show()

interact(
    grid_transform,
    a=(-3,3,0.1),
    b=(-3,3,0.1),
    c=(-3,3,0.1),
    d=(-3,3,0.1)
);

interactive(children=(FloatSlider(value=0.0, description='a', max=3.0, min=-3.0), FloatSlider(value=0.0, descr…

# 8️⃣ Neural Network Matrix Computation

Every neural network layer performs matrix multiplication.

$$
y = Wx + b
$$

This visualization demonstrates a simple neural layer.

In [9]:
input_vector = np.array([
    1,
    2,
    3
])

weights = np.array([
    [0.5,0.2,0.1],
    [0.3,0.7,0.4]
])

bias = np.array([
    0.1,
    0.2
])

output = weights @ input_vector + bias

print("Input Vector:")
print(input_vector)

print("\nWeight Matrix:")
print(weights)

print("\nBias:")
print(bias)

print("\nOutput:")
print(output)

Input Vector:
[1 2 3]

Weight Matrix:
[[0.5 0.2 0.1]
 [0.3 0.7 0.4]]

Bias:
[0.1 0.2]

Output:
[1.3 3.1]


# 🎯 Summary

You visualized:

✅ Matrix Addition

✅ Scalar Multiplication

✅ Matrix Multiplication

✅ Matrix Transformations

✅ Determinant

✅ Matrix Inverse

✅ Matrix Rank

✅ Neural Network Computation

These operations form the mathematical foundation of:

- Deep Learning
- Computer Vision
- NLP
- Reinforcement Learning
- Transformers
- Large Language Models