# Basis and Dimension

## Python Implementation

In this notebook, you will learn:

1. Creating Basis Vectors
2. Standard Basis
3. Linear Independence
4. Span of Vectors
5. Coordinate Representation
6. Basis Transformation
7. Finding Basis from a Matrix
8. Dimension Calculation
9. Column Space Basis
10. Basis using Rank
11. PCA Basis Example
12. Embedding Space Example

In [1]:
import numpy as np

print("NumPy Version:", np.__version__)

NumPy Version: 2.4.6


# What is a Basis?

A basis is a set of vectors that:

1. Are linearly independent
2. Span the vector space

Every vector in the space can be represented using basis vectors.

In [2]:
e1 = np.array([1, 0])

e2 = np.array([0, 1])

print("e1 =", e1)

print("e2 =", e2)

e1 = [1 0]
e2 = [0 1]


# Standard Basis of R²

$$
e_1 =
\begin{bmatrix}
1\\
0
\end{bmatrix}
$$

$$
e_2 =
\begin{bmatrix}
0\\
1
\end{bmatrix}
$$

In [3]:
standard_basis = np.array([
    [1,0],
    [0,1]
])

print(standard_basis)

[[1 0]
 [0 1]]


# Standard Basis of R³

In [4]:
basis_r3 = np.eye(3)

print(basis_r3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Linear Independence

Vectors are linearly independent if:

$$
c_1v_1 + c_2v_2 + ... + c_nv_n = 0
$$

only when all coefficients are zero.

In [5]:
vectors = np.array([
    [1,0],
    [0,1]
])

rank = np.linalg.matrix_rank(vectors)

print("Rank =", rank)

print(
    "Independent:",
    rank == vectors.shape[0]
)

Rank = 2
Independent: True


# Dependent Vectors

In [6]:
vectors = np.array([
    [1,2],
    [2,4]
])

rank = np.linalg.matrix_rank(vectors)

print("Rank =", rank)

print(
    "Independent:",
    rank == vectors.shape[0]
)

Rank = 1
Independent: False


# Span of Vectors

The span is the set of all possible linear combinations.

Example:

$$
v=c_1e_1+c_2e_2
$$

In [7]:
e1 = np.array([1,0])

e2 = np.array([0,1])

c1 = 3
c2 = 4

v = c1*e1 + c2*e2

print(v)

[3 4]


# Coordinate Representation

Any vector can be represented using basis vectors.

In [8]:
basis = np.array([
    [1,0],
    [0,1]
])

vector = np.array([
    5,
    2
])

coordinates = np.linalg.solve(
    basis,
    vector
)

print(coordinates)

[5. 2.]


# Non-Standard Basis

In [9]:
basis = np.array([
    [1,1],
    [1,-1]
])

vector = np.array([
    4,
    2
])

coordinates = np.linalg.solve(
    basis,
    vector
)

print(
    "Coordinates in new basis:"
)

print(coordinates)

Coordinates in new basis:
[3. 1.]


# Basis Transformation

Changing coordinates from one basis to another.

In [10]:
old_basis = np.eye(2)

new_basis = np.array([
    [1,1],
    [1,-1]
])

vector = np.array([
    3,
    2
])

new_coordinates = np.linalg.solve(
    new_basis,
    vector
)

print(new_coordinates)

[2.5 0.5]


# Finding Basis from a Matrix

Independent columns form a basis for the column space.

In [11]:
A = np.array([
    [1,2,3],
    [2,4,6],
    [1,1,1]
])

print(A)

print(
    "\nRank:",
    np.linalg.matrix_rank(A)
)

[[1 2 3]
 [2 4 6]
 [1 1 1]]

Rank: 2


# Dimension

Dimension equals the number of basis vectors.

In [12]:
basis = np.array([
    [1,0,0],
    [0,1,0],
    [0,0,1]
])

dimension = basis.shape[0]

print(
    "Dimension:",
    dimension
)

Dimension: 3


# Basis and Rank

Dimension of the column space equals rank.

In [13]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

rank = np.linalg.matrix_rank(A)

print(
    "Rank:",
    rank
)

print(
    "Dimension of Column Space:",
    rank
)

Rank: 2
Dimension of Column Space: 2


# Computing Column Space Basis

Using Singular Value Decomposition (SVD).

In [14]:
A = np.array([
    [1,2],
    [3,4],
    [5,6]
])

U,S,Vt = np.linalg.svd(A)

rank = np.linalg.matrix_rank(A)

basis = U[:, :rank]

print(
    "Basis for Column Space:\n"
)

print(basis)

Basis for Column Space:

[[-0.2298477   0.88346102]
 [-0.52474482  0.24078249]
 [-0.81964194 -0.40189603]]


# PCA Basis Example

Principal Component Analysis creates a new basis that captures maximum variance.

In [15]:
data = np.array([
    [1,2],
    [2,3],
    [3,4],
    [4,5]
])

covariance = np.cov(
    data.T
)

eigenvalues, eigenvectors = np.linalg.eig(
    covariance
)

print(
    "Principal Basis:"
)

print(eigenvectors)

Principal Basis:
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


# Embedding Space Example

Modern AI models represent information in high-dimensional vector spaces.

Examples:

- Word2Vec
- BERT
- GPT Embeddings

Each embedding vector is represented in a learned basis.

In [16]:
embedding = np.random.rand(768)

print(
    "Embedding Dimension:",
    embedding.shape[0]
)

Embedding Dimension: 768


# Basis Verification Function

A set of vectors forms a basis if:

1. They are independent
2. They span the space

In [17]:
def is_basis(vectors):

    rank = np.linalg.matrix_rank(vectors)

    return rank == vectors.shape[1]

basis_vectors = np.array([
    [1,0],
    [0,1]
])

print(
    is_basis(basis_vectors)
)

True


# Random Basis Generator

In [18]:
while True:

    A = np.random.randint(
        -5,
        6,
        (3,3)
    )

    if np.linalg.matrix_rank(A) == 3:
        break

print(
    "Random Basis Matrix:\n"
)

print(A)

Random Basis Matrix:

[[ 0 -1  0]
 [ 3 -5 -2]
 [ 1  2  4]]


# AI Perspective

Basis and Dimension are fundamental to:

- PCA
- SVD
- Autoencoders
- Embeddings
- Recommendation Systems
- Computer Vision
- Deep Learning

Every modern AI system learns useful basis representations of data.

# Key Takeaways

✅ Basis is a minimal set of independent vectors.

✅ Dimension equals the number of basis vectors.

✅ Every vector can be represented using basis vectors.

✅ Rank determines the dimension of the column space.

✅ PCA learns a new basis.

✅ Embeddings exist in learned vector spaces.

Basis and Dimension are the bridge between Linear Algebra and Modern AI.