# Orthogonality

## Python Implementation

Topics Covered

1. Dot Product
2. Orthogonal Vectors
3. Angle Between Vectors
4. Vector Norms
5. Orthonormal Vectors
6. Orthogonal Basis
7. Orthogonal Matrix Verification
8. Vector Projection
9. Gram-Schmidt Orthogonalization
10. QR Decomposition
11. PCA Orthogonality Example
12. Orthogonal Initialization in Deep Learning

In [1]:
import numpy as np

print("NumPy Version:", np.__version__)

NumPy Version: 2.4.6


# Dot Product

For vectors:

$$
u=[u_1,u_2]
$$

$$
v=[v_1,v_2]
$$

Dot Product:

$$
u^Tv
$$

In [2]:
u = np.array([1, 2])

v = np.array([3, 4])

dot_product = np.dot(u, v)

print("u =", u)
print("v =", v)

print("\nDot Product =", dot_product)

u = [1 2]
v = [3 4]

Dot Product = 11


# Orthogonal Vectors

Two vectors are orthogonal is:
$$
u^Tv=0
$$


In [3]:
u = np.array([1, 0])

v = np.array([0, 1])

dot_product = np.dot(u, v)

print("Dot Product =", dot_product)

if dot_product == 0:
    print("Vectors are Orthogonal")
else:
    print("Vectors are NOT Orthogonal")

Dot Product = 0
Vectors are Orthogonal


# Non-Orthogonal Example

In [4]:
u = np.array([1, 2])

v = np.array([3, 1])

print(
    "Dot Product:",
    np.dot(u, v)
)

Dot Product: 5


# Vector Norm

Magnitude of a vector:

$$
||u|| =\sqrt{x^2+y^2}
$$

In [5]:
u = np.array([3, 4])

norm = np.linalg.norm(u)

print("Norm =", norm)

Norm = 5.0


# Unit Vector

A vector with magnitude 1.

In [6]:
u = np.array([3, 4])

unit_u = u / np.linalg.norm(u)

print(unit_u)

print(
    "Norm:",
    np.linalg.norm(unit_u)
)

[0.6 0.8]
Norm: 1.0


# Orthonormal Vectors

Orthogonal + Unit Length

In [7]:
u = np.array([1,0])

v = np.array([0,1])

print(
    "Dot Product:",
    np.dot(u,v)
)

print(
    "Norm u:",
    np.linalg.norm(u)
)

print(
    "Norm v:",
    np.linalg.norm(v)
)

Dot Product: 0
Norm u: 1.0
Norm v: 1.0


# Angle Between Vectors

$$
\cos(\theta)
=
\frac{u^Tv}
{||u|| ||v||}
$$

In [8]:
u = np.array([1,2])

v = np.array([3,1])

cos_theta = (
    np.dot(u,v)
    /
    (
        np.linalg.norm(u)
        *
        np.linalg.norm(v)
    )
)

theta = np.degrees(
    np.arccos(cos_theta)
)

print(
    "Angle:",
    theta
)

Angle: 45.00000000000001


# Orthogonal Basis

A basis where all vectors are orthogonal.

In [9]:
basis = np.array([
    [1,0],
    [0,1]
])

for i in range(len(basis)):
    for j in range(i+1,len(basis)):
        print(
            np.dot(
                basis[i],
                basis[j]
            )
        )

0


# Orthogonal Matrix

A matrix is orthogonal if:
$$
Q^TQ=I
$$

In [12]:
Q = np.array([
    [0,-1],
    [1, 0]
])

result = Q.T @ Q

print(result)

[[1 0]
 [0 1]]


In [13]:
print(
    np.allclose(
        result,
        np.eye(2)
    )
)

True


# Vector Projection

Projection of x onto u:

$$
Proj_u(x)
=
\frac{x^Tu}{u^Tu}u
$$

In [14]:
x = np.array([4,3])

u = np.array([1,0])

projection = (
    np.dot(x,u)
    /
    np.dot(u,u)
) * u

print(projection)

[4. 0.]


# Gram-Schmidt Orthogonalization

Convert independent vectors into orthogonal vectors.

In [15]:
v1 = np.array(
    [1,1]
)

v2 = np.array(
    [1,0]
)

u1 = v1

u2 = (
    v2
    -
    (
        np.dot(v2,u1)
        /
        np.dot(u1,u1)
    ) * u1
)

print("u1 =", u1)

print("u2 =", u2)

print(
    "Dot Product:",
    np.dot(u1,u2)
)

u1 = [1 1]
u2 = [ 0.5 -0.5]
Dot Product: 0.0


# Normalized Gram-Schmidt

In [16]:
e1 = u1 / np.linalg.norm(u1)

e2 = u2 / np.linalg.norm(u2)

print(e1)

print(e2)

print(
    np.dot(e1,e2)
)

[0.70710678 0.70710678]
[ 0.70710678 -0.70710678]
0.0


# QR Decomposition

$$
A=QR
$$

Q = Orthogonal Matrix

R = Upper Triangular Matrix

In [17]:
A = np.array([
    [1,2],
    [3,4]
])

Q,R = np.linalg.qr(A)

print("Q =\n")
print(Q)

print("\nR =\n")
print(R)

Q =

[[-0.31622777 -0.9486833 ]
 [-0.9486833   0.31622777]]

R =

[[-3.16227766 -4.42718872]
 [ 0.         -0.63245553]]


In [18]:
print(
    "\nQᵀQ =\n"
)

print(
    Q.T @ Q
)


QᵀQ =

[[ 1.0000000e+00 -5.8339229e-18]
 [-5.8339229e-18  1.0000000e+00]]


# PCA Orthogonality

Principal Components are orthogonal directions.

In [19]:
from sklearn.decomposition import PCA

data = np.random.randn(
    500,
    5
)

pca = PCA(
    n_components=5
)

pca.fit(data)

components = pca.components_

print(
    components.shape
)

(5, 5)


In [20]:
orthogonality_check = (
    components
    @
    components.T
)

print(
    np.round(
        orthogonality_check,
        4
    )
)

[[ 1. -0.  0.  0.  0.]
 [-0.  1. -0. -0.  0.]
 [ 0. -0.  1.  0. -0.]
 [ 0. -0.  0.  1.  0.]
 [ 0.  0. -0.  0.  1.]]


# Orthogonal Initialization

Used in Deep Learning for stable training.

In [21]:
random_matrix = np.random.randn(
    5,
    5
)

Q,R = np.linalg.qr(
    random_matrix
)

weights = Q

print(
    "Orthogonal Weight Matrix:"
)

print(weights)

Orthogonal Weight Matrix:
[[-0.28213375  0.58023326 -0.53650374  0.04167479  0.5423623 ]
 [ 0.12926496 -0.56023726 -0.7112088   0.39879949 -0.06757063]
 [ 0.9490065   0.2481915  -0.08754277 -0.08991229  0.14845767]
 [-0.05101711  0.20101132 -0.44319162 -0.59887483 -0.63397306]
 [-0.02179525 -0.49745251 -0.04757349 -0.68737683  0.52660785]]


# High-Dimensional Orthogonality

Random vectors become nearly orthogonal in high dimensions.

In [22]:
v1 = np.random.randn(1000)

v2 = np.random.randn(1000)

cos_similarity = (
    np.dot(v1,v2)
    /
    (
        np.linalg.norm(v1)
        *
        np.linalg.norm(v2)
    )
)

print(
    "Cosine Similarity:",
    cos_similarity
)

Cosine Similarity: -0.022608296219210518


# Key Takeaways

✅ Orthogonal vectors contain independent information.

✅ Dot Product determines orthogonality.

✅ Orthogonal matrices preserve lengths and angles.

✅ Gram-Schmidt creates orthogonal bases.

✅ QR decomposition relies on orthogonality.

✅ PCA components are orthogonal.

✅ Orthogonality is fundamental in AI and Deep Learning.