# Matrix Operations in Python

In this notebook, we will implement:

- Matrix Creation
- Matrix Dimensions
- Matrix Addition
- Matrix Subtraction
- Scalar Multiplication
- Matrix Multiplication
- Transpose
- Determinant
- Inverse
- Rank

using NumPy.

Matrices are the foundation of Machine Learning and Deep Learning.

In [1]:
import numpy as np

print("NumPy Version:", np.__version__)

NumPy Version: 2.4.6


# Creating Matrices

A matrix is a rectangular arrangement of numbers organized into rows and columns.

In [2]:
A = np.array([
    [1, 2],
    [3, 4]
])

print(A)

[[1 2]
 [3 4]]


# Matrix Dimensions

The shape of a matrix tells us:

(Number of Rows, Number of Columns)

In [3]:
A = np.array([
    [1,2,3],
    [4,5,6]
])

print("Shape:", A.shape)

Shape: (2, 3)


# Matrix Addition

Two matrices of the same dimensions can be added element-wise.

In [4]:
A = np.array([
    [1,2],
    [3,4]
])

B = np.array([
    [5,6],
    [7,8]
])

C = A + B

print(C)

[[ 6  8]
 [10 12]]


# Matrix Subtraction

Subtraction is performed element-wise.

In [5]:
A = np.array([
    [5,6],
    [7,8]
])

B = np.array([
    [1,2],
    [3,4]
])

print(A - B)

[[4 4]
 [4 4]]


# Scalar Multiplication

A scalar multiplies every element of a matrix.

In [6]:
A = np.array([
    [1,2],
    [3,4]
])

print(3 * A)

[[ 3  6]
 [ 9 12]]


# Matrix Multiplication

Matrix multiplication is one of the most important operations in AI.

Neural networks perform billions of matrix multiplications.

In [7]:
A = np.array([
    [1,2],
    [3,4]
])

B = np.array([
    [5,6],
    [7,8]
])

C = A @ B

print(C)

[[19 22]
 [43 50]]


# Matrix Transpose

Rows become columns.

In [8]:
A = np.array([
    [1,2],
    [3,4]
])

print(A.T)

[[1 3]
 [2 4]]


# Identity Matrix

An identity matrix behaves like the number 1 in matrix algebra.

In [9]:
I = np.eye(3)

print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Determinant

The determinant helps determine whether a matrix is invertible.

In [10]:
A = np.array([
    [1,2],
    [3,4]
])

det = np.linalg.det(A)

print(det)

-2.0000000000000004


# Matrix Inverse

The inverse matrix reverses a matrix transformation.

In [11]:
A = np.array([
    [1,2],
    [3,4]
])

A_inv = np.linalg.inv(A)

print(A_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


# Matrix Rank

Rank tells us how many independent rows or columns exist.

In [12]:
A = np.array([
    [1,2],
    [2,4]
])

rank = np.linalg.matrix_rank(A)

print(rank)

1


# Solving Linear Equations

Many Machine Learning problems can be expressed as systems of equations.

In [13]:
A = np.array([
    [2,1],
    [1,3]
])

b = np.array([8,13])

x = np.linalg.solve(A,b)

print(x)

[2.2 3.6]


# Matrix Operations in Machine Learning

Feature Matrix:

Rows → Samples

Columns → Features

Example:

$$
X=
\begin{bmatrix}
Age & Salary & Experience
\end{bmatrix}
$$

Most machine learning algorithms operate directly on feature matrices.

In [14]:
X = np.array([
    [25,50000,2],
    [30,70000,5],
    [35,90000,8]
])

print("Feature Matrix:")
print(X)

print("\nShape:", X.shape)

Feature Matrix:
[[   25 50000     2]
 [   30 70000     5]
 [   35 90000     8]]

Shape: (3, 3)


# Summary

In this notebook, you learned:

✅ Matrix Creation

✅ Matrix Dimensions

✅ Matrix Addition

✅ Matrix Subtraction

✅ Scalar Multiplication

✅ Matrix Multiplication

✅ Transpose

✅ Identity Matrix

✅ Determinant

✅ Inverse Matrix

✅ Rank

✅ Solving Linear Systems

These operations form the foundation of:

- Machine Learning
- Deep Learning
- Computer Vision
- Robotics
- Large Language Models