# 🌌 Vector Spaces in Python

In this notebook, we will learn:

1. Creating Vector Spaces
2. Linear Combinations
3. Span of Vectors
4. Subspace Verification
5. Basis Vectors
6. Dimension Calculation
7. Coordinate Representation
8. Feature Spaces
9. Embedding Spaces
10. Vector Space Operations using NumPy

Vector Spaces are the mathematical foundation of modern Artificial Intelligence.

Every feature vector, embedding vector, and latent representation exists inside a vector space.

In [1]:
import numpy as np

np.set_printoptions(
    suppress=True,
    precision=3
)

print("NumPy Imported Successfully")

NumPy Imported Successfully


# 1️⃣ Creating Vector Spaces

A vector space is a collection of vectors that supports:

- Vector Addition
- Scalar Multiplication

The most common vector spaces are:

\[
\mathbb{R}^2
\]

and

\[
\mathbb{R}^3
\]

In [2]:
v1 = np.array([1,2])

v2 = np.array([3,4])

print("Vector 1:", v1)
print("Vector 2:", v2)

Vector 1: [1 2]
Vector 2: [3 4]


# 2️⃣ Linear Combinations

A linear combination is:

\[
a_1v_1+a_2v_2+\cdots+a_nv_n
\]

where:

- \(a_i\) are scalars
- \(v_i\) are vectors

Linear combinations generate new vectors inside the same vector space.

In [3]:
v1 = np.array([1,0])

v2 = np.array([0,1])

a = 3
b = 5

result = a*v1 + b*v2

print("Linear Combination:")
print(result)

Linear Combination:
[3 5]


# 3️⃣ Span of Vectors

The span of vectors is the set of all possible linear combinations.

Example:

\[
Span(v_1,v_2)
\]

represents every vector reachable using \(v_1\) and \(v_2\).

In [4]:
v1 = np.array([1,0])

v2 = np.array([0,1])

for a in range(-2,3):
    
    for b in range(-2,3):
        
        point = a*v1 + b*v2
        
        print(point)

[-2 -2]
[-2 -1]
[-2  0]
[-2  1]
[-2  2]
[-1 -2]
[-1 -1]
[-1  0]
[-1  1]
[-1  2]
[ 0 -2]
[ 0 -1]
[0 0]
[0 1]
[0 2]
[ 1 -2]
[ 1 -1]
[1 0]
[1 1]
[1 2]
[ 2 -2]
[ 2 -1]
[2 0]
[2 1]
[2 2]


# 4️⃣ Subspace Verification

A subspace must satisfy:

1. Contains Zero Vector
2. Closed Under Addition
3. Closed Under Scalar Multiplication

Example:

\[
S=
\{(x,y):y=0\}
\]

is a subspace of \(\mathbb{R}^2\).

In [5]:
u = np.array([2,0])

v = np.array([5,0])

print("u + v =", u + v)

print("3u =", 3*u)

u + v = [7 0]
3u = [6 0]


# 5️⃣ Basis Vectors

A basis is a set of vectors that:

- Are linearly independent
- Span the entire vector space

Standard basis of:

\[
\mathbb{R}^2
\]

is:

\[
e_1=
\begin{bmatrix}
1\\
0
\end{bmatrix}
,
e_2=
\begin{bmatrix}
0\\
1
\end{bmatrix}
\]

In [6]:
e1 = np.array([1,0])

e2 = np.array([0,1])

print("Basis Vector e1:", e1)
print("Basis Vector e2:", e2)

Basis Vector e1: [1 0]
Basis Vector e2: [0 1]


# 6️⃣ Dimension Calculation

The dimension of a vector space is the number of vectors in its basis.

Examples:

\[
dim(\mathbb{R}^2)=2
\]

\[
dim(\mathbb{R}^3)=3
\]

In [7]:
basis = np.array([
    [1,0,0],
    [0,1,0],
    [0,0,1]
])

dimension = basis.shape[0]

print("Dimension:", dimension)

Dimension: 3


# 7️⃣ Coordinate Representation

Any vector can be represented as a combination of basis vectors.

Example:

\[
v=
\begin{bmatrix}
4\\
7
\end{bmatrix}
\]

can be written as:

\[
4e_1+7e_2
\]

In [8]:
e1 = np.array([1,0])

e2 = np.array([0,1])

v = 4*e1 + 7*e2

print(v)

[4 7]


# 8️⃣ Feature Spaces

Machine Learning datasets create feature spaces.

Example:

Features:

- Age
- Salary
- Experience

Every sample becomes a vector.

In [9]:
X = np.array([
    [25,50000,2],
    [30,70000,5],
    [35,90000,8]
])

print("Feature Space:")
print(X)

print("\nShape:", X.shape)

Feature Space:
[[   25 50000     2]
 [   30 70000     5]
 [   35 90000     8]]

Shape: (3, 3)


# 9️⃣ Embedding Spaces

Modern AI models convert objects into vectors.

Examples:

- Words
- Images
- Audio
- Videos

These vectors live in high-dimensional embedding spaces.

In [10]:
embedding_dimension = 8

word_embedding = np.random.rand(
    embedding_dimension
)

print("Embedding Vector:")
print(word_embedding)

print("\nDimension:", len(word_embedding))

Embedding Vector:
[0.489 0.827 0.168 0.044 0.885 0.739 0.843 0.245]

Dimension: 8


# 🔟 Vector Space Operations using NumPy

Common operations:

- Addition
- Subtraction
- Scalar Multiplication
- Dot Product
- Norm

In [11]:
u = np.array([2,3])

v = np.array([4,5])

print("Addition:")
print(u + v)

print("\nSubtraction:")
print(u - v)

print("\nScalar Multiplication:")
print(3*u)

print("\nDot Product:")
print(np.dot(u,v))

print("\nNorm:")
print(np.linalg.norm(u))

Addition:
[6 8]

Subtraction:
[-2 -2]

Scalar Multiplication:
[6 9]

Dot Product:
23

Norm:
3.605551275463989


# 🤖 Vector Spaces in Artificial Intelligence

Vector Spaces are used in:

### Machine Learning

Feature Vectors

### Computer Vision

Image Embeddings

### Natural Language Processing

Word Embeddings

### Transformers

Token Embeddings

### Recommendation Systems

User and Item Embeddings

### Generative AI

Latent Spaces

Every modern AI model learns representations inside vector spaces.

# 📌 Summary

In this notebook, you learned:

✅ Creating Vector Spaces

✅ Linear Combinations

✅ Span of Vectors

✅ Subspace Verification

✅ Basis Vectors

✅ Dimension Calculation

✅ Coordinate Representation

✅ Feature Spaces

✅ Embedding Spaces

✅ Vector Space Operations using NumPy

These concepts form the mathematical foundation for:

- Linear Independence
- Basis and Dimension
- Orthogonality
- Eigenvalues
- Eigenvectors
- PCA
- SVD
- Deep Learning
- Large Language Models