# Determinants

## Python Implementation

In this notebook we will learn:

1. Determinants of 2×2 Matrices
2. Determinants of 3×3 Matrices
3. Determinants using NumPy
4. Determinants using Cofactor Expansion
5. Singular vs Non-Singular Matrices
6. Determinants and Matrix Inverses
7. Determinants in Machine Learning
8. Determinants of Large Matrices

In [1]:
import numpy as np

print("NumPy Version:", np.__version__)

NumPy Version: 2.4.6


# Determinant of a 2×2 Matrix

Given:

$$
A=
\begin{bmatrix}
a & b\\
c & d
\end{bmatrix}
$$

Determinant:

$$
det(A)=ad-bc
$$

In [2]:
A = np.array([
    [2,3],
    [1,4]
])

print(A)

[[2 3]
 [1 4]]


In [3]:
det = np.linalg.det(A)

print("Determinant =", det)

Determinant = 5.000000000000001


# Computing Determinant Manually

In [4]:
a,b = 2,3
c,d = 1,4

det = a*d - b*c

print(det)

5


# Determinant of a 3×3 Matrix

In [5]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,10]
])

print(A)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]


In [6]:
det = np.linalg.det(A)

print("Determinant =", det)

Determinant = -2.9999999999999996


# Cofactor Expansion

For a 3×3 matrix:

$$
det(A)=
a(ei−fh)
-b(di−fg)
+c(dh−eg)
$$

In [7]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,10]
])

a,b,c = A[0]

d,e,f = A[1]

g,h,i = A[2]

det = (
    a*(e*i - f*h)
    - b*(d*i - f*g)
    + c*(d*h - e*g)
)

print(det)

-3


# Singular Matrix

A matrix is singular when:

$$
det(A)=0
$$
Such matrices cannot be inverted.

In [8]:
A = np.array([
    [1,2],
    [2,4]
])

print(A)

print(
    "Determinant:",
    np.linalg.det(A)
)

[[1 2]
 [2 4]]
Determinant: 0.0


# Non-Singular Matrix

A matrix is invertible when:

$$
det(A)\neq0
$$

In [9]:
A = np.array([
    [2,3],
    [1,4]
])

print(
    "Determinant:",
    np.linalg.det(A)
)

print(
    "\nInverse Matrix:\n",
    np.linalg.inv(A)
)

Determinant: 5.000000000000001

Inverse Matrix:
 [[ 0.8 -0.6]
 [-0.2  0.4]]


# Determinants and Matrix Inverses

The determinant determines whether an inverse exists.

In [10]:
matrices = [

    np.array([
        [2,3],
        [1,4]
    ]),

    np.array([
        [1,2],
        [2,4]
    ])
]

for i,A in enumerate(matrices):

    print(f"\nMatrix {i+1}")

    det = np.linalg.det(A)

    print("Determinant:", det)

    if abs(det) > 1e-10:
        print("Invertible")

    else:
        print("Not Invertible")


Matrix 1
Determinant: 5.000000000000001
Invertible

Matrix 2
Determinant: 0.0
Not Invertible


# Determinant of Random Matrices

In [11]:
for size in [2,3,4,5]:

    A = np.random.randint(
        1,
        10,
        (size,size)
    )

    det = np.linalg.det(A)

    print("\nSize:", size)

    print(A)

    print(
        "Determinant:",
        round(det,2)
    )


Size: 2
[[3 3]
 [1 9]]
Determinant: 24.0

Size: 3
[[5 9 3]
 [3 5 9]
 [9 1 5]]
Determinant: 548.0

Size: 4
[[6 5 9 8]
 [5 9 3 4]
 [3 2 9 1]
 [4 1 5 7]]
Determinant: -257.0

Size: 5
[[7 9 1 2 7]
 [6 8 5 1 7]
 [2 4 5 3 8]
 [6 1 3 3 2]
 [3 1 4 2 6]]
Determinant: -2087.0


# Determinants and Area Scaling

Consider:

$$
A=
\begin{bmatrix}
2 & 0\\
0 & 3
\end{bmatrix}
$$

Area scales by:

$$
det(A)=6
$$

In [12]:
A = np.array([
    [2,0],
    [0,3]
])

print(A)

print(
    "Scaling Factor:",
    np.linalg.det(A)
)

[[2 0]
 [0 3]]
Scaling Factor: 6.0


# Determinants in Machine Learning

Principal Component Analysis (PCA)

Requires solving:

$$
det(A-\lambda I)=0
$$

to find eigenvalues.

In [13]:
covariance_matrix = np.array([
    [4,2],
    [2,3]
])

print(
    "Covariance Matrix:\n",
    covariance_matrix
)

print(
    "\nDeterminant:",
    np.linalg.det(
        covariance_matrix
    )
)

Covariance Matrix:
 [[4 2]
 [2 3]]

Determinant: 7.999999999999998


# Characteristic Equation

Used in Eigenvalue Computation

$$
det(A-\lambda I)=0
$$

In [14]:
A = np.array([
    [4,2],
    [1,3]
])

eigenvalues = np.linalg.eigvals(A)

print(
    "Eigenvalues:"
)

print(
    eigenvalues
)

Eigenvalues:
[5. 2.]


# Performance Benchmark

Determinant computation becomes expensive for large matrices.

In [15]:
import time

sizes = [10,50,100]

for n in sizes:

    A = np.random.rand(n,n)

    start = time.time()

    np.linalg.det(A)

    end = time.time()

    print(
        f"{n}x{n} Matrix:",
        round(end-start,4),
        "seconds"
    )

10x10 Matrix: 0.0001 seconds
50x50 Matrix: 0.0002 seconds
100x100 Matrix: 0.0004 seconds


# AI Example

Determinants appear in:

- PCA
- Covariance Matrices
- Gaussian Distributions
- Bayesian Models
- Computer Vision
- Robotics
- Deep Learning
- State Estimation