# 🔄 Linear Transformations in Python

In this notebook, we will learn:

1. Creating Transformation Matrices
2. Matrix-Vector Multiplication
3. Scaling Transformation
4. Rotation Transformation
5. Reflection Transformation
6. Shear Transformation
7. Composition of Transformations
8. Transforming Point Clouds
9. Image Transformations
10. Linear Transformations in AI

Linear Transformations are the mathematical foundation of:

- Neural Networks
- Computer Vision
- Robotics
- Computer Graphics
- Transformers

In [1]:
import numpy as np

np.set_printoptions(
    precision=3,
    suppress=True
)

print("NumPy Imported Successfully")

NumPy Imported Successfully


# 1️⃣ Creating Transformation Matrices

A Linear Transformation can be represented as:

$$
T(x)=Ax
$$

where:

- A is a matrix
- x is a vector

The matrix determines how the vector changes.

In [2]:
A = np.array([
    [2,0],
    [0,2]
])

print("Transformation Matrix:")
print(A)

Transformation Matrix:
[[2 0]
 [0 2]]


# 2️⃣ Matrix-Vector Multiplication

Applying a transformation means multiplying:

$$
Ax
$$

where:

$$
x=
\begin{bmatrix}
x\\
y
\end{bmatrix}
$$

In [3]:
A = np.array([
    [2,0],
    [0,2]
])

x = np.array([
    3,
    4
])

result = A @ x

print("Original Vector:")
print(x)

print("\nTransformed Vector:")
print(result)

Original Vector:
[3 4]

Transformed Vector:
[6 8]


# 3️⃣ Scaling Transformation

Scaling changes the size of a vector.

Scaling Matrix:
$$
\begin{bmatrix}
s_x&0\\
0&s_y
\end{bmatrix}
$$

In [4]:
scale = np.array([
    [3,0],
    [0,2]
])

vector = np.array([2,3])

scaled_vector = scale @ vector

print("Original:", vector)
print("Scaled:", scaled_vector)

Original: [2 3]
Scaled: [6 6]


# 4️⃣ Rotation Transformation

Rotation rotates vectors around the origin.

Rotation Matrix:

$$
\begin{bmatrix}
\cos\theta&-\sin\theta\\
\sin\theta&\cos\theta
\end{bmatrix}
$$

In [5]:
theta = np.radians(45)

rotation = np.array([
    [np.cos(theta), -np.sin(theta)],
    [np.sin(theta),  np.cos(theta)]
])

vector = np.array([1,0])

rotated = rotation @ vector

print("Original:", vector)
print("Rotated :", rotated)

Original: [1 0]
Rotated : [0.707 0.707]


# 5️⃣ Reflection Transformation

Reflection mirrors vectors across an axis.

Reflection about x-axis:

$$
\begin{bmatrix}
1&0\\
0&-1
\end{bmatrix}
$$

In [6]:
reflection = np.array([
    [1,0],
    [0,-1]
])

vector = np.array([3,4])

reflected = reflection @ vector

print("Original :", vector)
print("Reflected:", reflected)

Original : [3 4]
Reflected: [ 3 -4]


# 6️⃣ Shear Transformation

Shearing slants the shape while preserving parallel lines.

Shear Matrix:

$$
\begin{bmatrix}
1&k\\
0&1
\end{bmatrix}
$$

In [7]:
k = 1.5

shear = np.array([
    [1,k],
    [0,1]
])

vector = np.array([2,3])

sheared = shear @ vector

print("Original:", vector)
print("Sheared :", sheared)

Original: [2 3]
Sheared : [6.5 3. ]


# 7️⃣ Composition of Transformations

Multiple transformations can be combined.

If:

$$
T_1=A
$$

and

$$
T_2=B
$$

Then:

$$
T=B A
$$

This is called Composition.

In [8]:
scale = np.array([
    [2,0],
    [0,2]
])

theta = np.radians(45)

rotation = np.array([
    [np.cos(theta),-np.sin(theta)],
    [np.sin(theta), np.cos(theta)]
])

combined = rotation @ scale

print(combined)

[[ 1.414 -1.414]
 [ 1.414  1.414]]


# Applying Combined Transformation

We can apply multiple transformations in a single step.

In [9]:
vector = np.array([1,1])

result = combined @ vector

print("Original :", vector)
print("Transformed:", result)

Original : [1 1]
Transformed: [0.    2.828]


# 8️⃣ Transforming Point Clouds

A point cloud is a collection of points.

Transformations can be applied to all points simultaneously.

In [10]:
points = np.array([
    [1,1],
    [2,1],
    [2,2],
    [1,2]
])

scale = np.array([
    [2,0],
    [0,2]
])

transformed_points = points @ scale.T

print(transformed_points)

[[2 2]
 [4 2]
 [4 4]
 [2 4]]


# 9️⃣ Image Transformations

Images are matrices.

Transformation matrices are used for:

- Rotation
- Scaling
- Reflection
- Warping

Computer Vision systems apply these operations constantly.

In [11]:
image = np.random.randint(
    0,
    255,
    (5,5)
)

print("Image Matrix:")
print(image)

Image Matrix:
[[  2 184 154 237 107]
 [ 56 170  70  30  40]
 [153 213 231 227 185]
 [202 203 107  34  68]
 [ 99 115  62 205  87]]


# 🔟 Linear Transformations in NumPy

NumPy provides efficient matrix operations.

Common Functions:

- np.dot()
- @ operator
- np.matmul()

In [12]:
A = np.array([
    [1,2],
    [3,4]
])

B = np.array([
    [5,6],
    [7,8]
])

print("Using @")
print(A @ B)

print("\nUsing np.matmul")
print(np.matmul(A,B))

Using @
[[19 22]
 [43 50]]

Using np.matmul
[[19 22]
 [43 50]]


# 🤖 Linear Transformations in Artificial Intelligence

Every Neural Network Layer computes:

$$
y = Wx+b
$$

where:

- W is a transformation matrix
- x is an input vector

The matrix multiplication:

$$
Wx
$$

is a Linear Transformation.

---

Applications:

### Machine Learning

Feature Transformations

### Computer Vision

Image Augmentation

### NLP

Word Embeddings

### Transformers

Query, Key, Value Projections

### Robotics

Coordinate Transformations

### Computer Graphics

3D Rendering Pipelines

In [13]:
input_vector = np.array([
    1.0,
    2.0,
    3.0
])

weights = np.array([
    [0.2,0.5,0.1],
    [0.3,0.7,0.4]
])

output = weights @ input_vector

print("Input:")
print(input_vector)

print("\nOutput:")
print(output)

Input:
[1. 2. 3.]

Output:
[1.5 2.9]


# 📌 Summary

In this notebook, you learned:

✅ Creating Transformation Matrices

✅ Matrix-Vector Multiplication

✅ Scaling

✅ Rotation

✅ Reflection

✅ Shearing

✅ Composition

✅ Point Cloud Transformations

✅ Image Transformations

✅ Neural Network Transformations

Linear Transformations are the foundation of:

- Neural Networks
- Transformers
- PCA
- SVD
- Computer Vision
- Robotics