# Tensors in Python

In this notebook, we will learn:

1. Creating Tensors
2. Tensor Shapes
3. Tensor Rank
4. Tensor Reshaping
5. Tensor Transpose
6. Tensor Addition
7. Tensor Broadcasting
8. Tensor Multiplication
9. Tensor Slicing
10. Tensor Operations with NumPy
11. Tensor Operations with PyTorch
12. Tensor Operations with TensorFlow

Tensors are the fundamental data structure of modern Artificial Intelligence.

In [1]:
import numpy as np

print("NumPy Version:", np.__version__)

NumPy Version: 2.4.6


# Creating Tensors

A tensor is a multidimensional array.

Examples:

- Scalar → Rank 0
- Vector → Rank 1
- Matrix → Rank 2
- Higher Dimensional Arrays → Rank 3+

In [2]:
scalar = np.array(5)

vector = np.array([1,2,3])

matrix = np.array([
    [1,2],
    [3,4]
])

tensor3d = np.array([
    [
        [1,2],
        [3,4]
    ],
    [
        [5,6],
        [7,8]
    ]
])

print("Scalar:\n", scalar)
print("\nVector:\n", vector)
print("\nMatrix:\n", matrix)
print("\nTensor:\n", tensor3d)

Scalar:
 5

Vector:
 [1 2 3]

Matrix:
 [[1 2]
 [3 4]]

Tensor:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# Tensor Shapes

The shape tells us the size of every dimension.

In [3]:
tensor = np.array([
    [
        [1,2],
        [3,4]
    ],
    [
        [5,6],
        [7,8]
    ]
])

print("Shape:", tensor.shape)

Shape: (2, 2, 2)


# Tensor Rank

Rank represents the number of dimensions.

In [4]:
scalar = np.array(10)

vector = np.array([1,2,3])

matrix = np.array([
    [1,2],
    [3,4]
])

tensor = np.random.rand(2,3,4)

print("Scalar Rank:", scalar.ndim)
print("Vector Rank:", vector.ndim)
print("Matrix Rank:", matrix.ndim)
print("Tensor Rank:", tensor.ndim)

Scalar Rank: 0
Vector Rank: 1
Matrix Rank: 2
Tensor Rank: 3


# Tensor Reshaping

Reshaping changes dimensions without changing data.

In [5]:
tensor = np.arange(12)

print("Original:")
print(tensor)

reshaped = tensor.reshape(3,4)

print("\nReshaped:")
print(reshaped)

Original:
[ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


# Tensor Transpose

Transpose swaps dimensions.

In [6]:
matrix = np.array([
    [1,2,3],
    [4,5,6]
])

print("Original:")
print(matrix)

print("\nTranspose:")
print(matrix.T)

Original:
[[1 2 3]
 [4 5 6]]

Transpose:
[[1 4]
 [2 5]
 [3 6]]


# Tensor Addition

Addition is performed element-wise.

In [7]:
A = np.array([
    [1,2],
    [3,4]
])

B = np.array([
    [5,6],
    [7,8]
])

C = A + B

print(C)

[[ 6  8]
 [10 12]]


# Tensor Broadcasting

Broadcasting automatically expands dimensions.

In [8]:
A = np.array([
    [1,2,3],
    [4,5,6]
])

B = np.array([10,20,30])

print(A + B)

[[11 22 33]
 [14 25 36]]


# Tensor Multiplication

Element-wise multiplication.

In [9]:
A = np.array([
    [1,2],
    [3,4]
])

B = np.array([
    [5,6],
    [7,8]
])

print(A * B)

[[ 5 12]
 [21 32]]


# Matrix Multiplication

Different from element-wise multiplication.

In [10]:
A = np.array([
    [1,2],
    [3,4]
])

B = np.array([
    [5,6],
    [7,8]
])

print(A @ B)

[[19 22]
 [43 50]]


# Tensor Slicing

Access specific portions of a tensor.

In [11]:
tensor = np.array([
    [
        [1,2],
        [3,4]
    ],
    [
        [5,6],
        [7,8]
    ]
])

print(tensor[0])

print("\n")

print(tensor[:,:,1])

[[1 2]
 [3 4]]


[[2 4]
 [6 8]]


# Tensor Statistics

Useful for Machine Learning preprocessing.

In [12]:
tensor = np.random.rand(5,5)

print("Mean:", np.mean(tensor))
print("Max :", np.max(tensor))
print("Min :", np.min(tensor))
print("Std :", np.std(tensor))

Mean: 0.5306926704603862
Max : 0.9873928174022136
Min : 0.00592911691251119
Std : 0.28344603458644146


# Tensor Operations with NumPy

NumPy is the foundation of scientific computing.

In [13]:
tensor = np.random.rand(3,3)

print("Tensor:")
print(tensor)

print("\nSum:")
print(np.sum(tensor))

print("\nMean:")
print(np.mean(tensor))

print("\nShape:")
print(tensor.shape)

Tensor:
[[0.3400056  0.31938994 0.75771037]
 [0.61431175 0.79510952 0.49822426]
 [0.2522079  0.99655729 0.13405833]]

Sum:
4.707574962039439

Mean:
0.5230638846710488

Shape:
(3, 3)


# Tensor Operations with PyTorch

PyTorch tensors power modern Deep Learning.

In [14]:
import torch

tensor = torch.tensor([
    [1,2],
    [3,4]
])

print(tensor)

print("\nShape:")
print(tensor.shape)

print("\nRank:")
print(tensor.ndim)

tensor([[1, 2],
        [3, 4]])

Shape:
torch.Size([2, 2])

Rank:
2


In [15]:
A = torch.tensor([
    [1,2],
    [3,4]
])

B = torch.tensor([
    [5,6],
    [7,8]
])

print(A + B)

print("\n")

print(torch.matmul(A,B))

tensor([[ 6,  8],
        [10, 12]])


tensor([[19, 22],
        [43, 50]])


# GPU Acceleration with PyTorch

PyTorch can move tensors to the GPU.

In [16]:
import torch

device = (
    "cuda"
    if torch.cuda.is_available()
    else "cpu"
)

print("Device:", device)

tensor = torch.rand(
    (3,3),
    device=device
)

print(tensor)

Device: cpu
tensor([[0.0900, 0.7385, 0.4089],
        [0.6475, 0.9073, 0.7453],
        [0.5191, 0.3820, 0.2176]])


# Summary

You learned:

✅ Tensor Creation

✅ Tensor Shape

✅ Tensor Rank

✅ Tensor Reshaping

✅ Tensor Transpose

✅ Tensor Addition

✅ Tensor Broadcasting

✅ Tensor Multiplication

✅ Tensor Slicing

✅ NumPy Tensors

✅ PyTorch Tensors

These concepts form the computational foundation of:

- Deep Learning
- Computer Vision
- NLP
- Transformers
- Large Language Models
- Generative AI